"""Shell completion support for the outlook-cli command.

bash / zsh / fish / powershell completions are produced dynamically by
``argcomplete``, which reads the live argparse parser at completion time.
Nushell has no
argparse bridge, so we walk the parser ourselves and emit a static module of
``extern`` definitions (plus ``@completer`` commands for ``choices=[...]``
arguments).

Both are exposed through ``outlook-cli completion <shell>``.
"""

from __future__ import annotations

import argparse
import sys

SHELLS = ("bash", "zsh", "fish", "powershell", "nushell")


# ── parser introspection ──────────────────────────────────────────────


def _find_subparsers(
    parser: argparse.ArgumentParser,
) -> argparse._SubParsersAction | None:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _walk(
    parser: argparse.ArgumentParser,
    path: list[str],
    nodes: list[tuple[list[str], argparse.ArgumentParser]],
) -> None:
    nodes.append((path, parser))
    sub = _find_subparsers(parser)
    if sub is None:
        return
    seen: set[int] = set()
    for name, child in sub.choices.items():
        # subparser aliases point at the same parser object; visit once.
        if id(child) in seen:
            continue
        seen.add(id(child))
        _walk(child, path + [name], nodes)


# ── nushell emitter ───────────────────────────────────────────────────


def _nu_type(action: argparse.Action) -> str:
    if action.type is int:
        return "int"
    return "string"


def _nu_string(value: str) -> str:
    """Quote a value for a nushell list literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _nu_comment(action: argparse.Action) -> str:
    if not action.help or action.help is argparse.SUPPRESS:
        return ""
    text = " ".join(action.help.split())
    return f"  # {text}"


def _nushell_module(parser: argparse.ArgumentParser, prog: str) -> str:
    nodes: list[tuple[list[str], argparse.ArgumentParser]] = []
    _walk(parser, [], nodes)

    completers: list[str] = []
    externs: list[str] = []

    for path, node in nodes:
        command = " ".join([prog, *path])
        positionals: list[str] = []
        flags: list[str] = []

        for action in node._actions:
            if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction)):
                continue

            # Resolve a completer for constrained-choice arguments.
            completer_ref = ""
            if action.choices:
                completer_name = "nu-complete " + " ".join(
                    [prog, *path, action.dest]
                )
                values = " ".join(_nu_string(str(c)) for c in action.choices)
                completers.append(
                    f'def "{completer_name}" [] {{ [{values}] }}'
                )
                completer_ref = f'@"{completer_name}"'

            if not action.option_strings:
                # positional
                optional = action.nargs in ("?", "*") or not action.required
                suffix = "?" if optional else ""
                decl = f"  {action.dest}{suffix}: {_nu_type(action)}{completer_ref}"
                positionals.append(decl + _nu_comment(action))
                continue

            longs = [o for o in action.option_strings if o.startswith("--")]
            shorts = [
                o
                for o in action.option_strings
                if o.startswith("-") and not o.startswith("--")
            ]
            name = longs[0] if longs else action.option_strings[0]
            if shorts:
                name = f"{name}({shorts[0]})"

            takes_value = not isinstance(
                action,
                (
                    argparse._StoreTrueAction,
                    argparse._StoreFalseAction,
                    argparse._CountAction,
                ),
            )
            if takes_value:
                decl = f"  {name}: {_nu_type(action)}{completer_ref}"
            else:
                decl = f"  {name}"
            flags.append(decl + _nu_comment(action))

        body = positionals + flags
        if body:
            externs.append(
                f'export extern "{command}" [\n' + "\n".join(body) + "\n]"
            )
        else:
            externs.append(f'export extern "{command}" []')

    header = (
        "# Nushell completions for outlook-cli (generated by "
        "`outlook-cli completion nushell`).\n"
        "#\n"
        "# Load it from your config, e.g.:\n"
        "#   outlook-cli completion nushell | save -f ~/.cache/outlook-cli.nu\n"
        "#   # then in config.nu:\n"
        "#   source ~/.cache/outlook-cli.nu\n"
    )
    parts = [header]
    if completers:
        # de-duplicate completer definitions while preserving order.
        seen: set[str] = set()
        unique = [c for c in completers if not (c in seen or seen.add(c))]
        parts.append("\n".join(unique))
    parts.append("\n\n".join(externs))
    return "\n\n".join(parts) + "\n"


# ── entry point ───────────────────────────────────────────────────────


def print_completion(shell: str, parser: argparse.ArgumentParser, prog: str = "outlook-cli") -> None:
    if shell == "nushell":
        sys.stdout.write(_nushell_module(parser, prog))
        return

    try:
        import argcomplete
    except ImportError:
        sys.stderr.write(
            "argcomplete is required for bash/zsh/fish/powershell completions.\n"
            "Install it with:  pip install argcomplete\n"
        )
        sys.exit(1)

    sys.stdout.write(argcomplete.shellcode([prog], shell=shell))
